### ISSUE TITLE
Error when start cachè in docker

### ISSUE THREAD

**Issue by poppogbr** [zrml/ccontainermain#14]
Hi,
when i run the container i have this error:
docker run -p 57779:57772 -p 1979:1972 cachedb:2017
2017/11/13 09:40:32 Starting Caché...
2017/11/13 09:40:34 Something is preventing Caché from starting in multi-user mode,
2017/11/13 09:40:34 You might want to start the container with the flag -cstart=false to fix it.
2017/11/13 09:40:34 Error: Caché was not brought up successfully.

**Comment by daimor** [comment]
Hi, can you put your Dockerfile here?
you add flag '-cconsole', in this case full cconsole log will be available in the output, and you can get more information about error.

**Comment by poppogbr** [comment]
FROM centos:7

# setup vars section___________________________________________________________________
#
ENV TMP_INSTALL_DIR="/tmp/cachekit"

# vars for Caché silent install
ENV ISC_PACKAGE_INSTANCENAME="CACHE" \
    ISC_PACKAGE_INSTALLDIR="/opt/ensemble/" \
    ISC_PACKAGE_UNICODE="Y"

# Caché distribution file________________________________________________________________
# set-up and install Caché from distrib_tmp dir
RUN mkdir $TMP_INSTALL_DIR
WORKDIR $TMP_INSTALL_DIR

#proxy setting for update from yum
ENV http_proxy "http://m.polenta:MartiTauk2%21@proxy.reply.it:8080"

# update OS + dependencies & run Caché silent install___________________________________
RUN yum -y update \
 && yum -y install which tar hostname net-tools wget \
 && yum -y clean all \ 
 && ln -sf /etc/locatime /usr/share/zoneinfo/Europe/Prague

COPY cache-2017.1.1.111.0su-lnxrhx64.tar $TMP_INSTALL_DIR/
RUN tar -xvf cache-2017.1.1.111.0su-lnxrhx64.tar -C .
RUN ./cinstall_silent
RUN rm -rf $TMP_INSTALL_DIR/*
RUN ccontrol stop $ISC_PACKAGE_INSTANCENAME quietly 

# TCP sockets that can be accessed if user wants to (see 'docker run -p' flag)
EXPOSE 57772 1972

# Caché container main process PID 1 (https://github.com/zrml/ccontainermain)
WORKDIR /
ADD ccontainermain .

ENTRYPOINT ["/ccontainermain"]

# run via:
# docker run -d -p 57779:57772 -p 1979:1972 <docker_image_id>
#
# more options & explinations
# $ docker run -d			// detached in the background; accessed only via network
# -h <host_name>			// you can specify a host name
# -p 57772:57772 			// TCP socket port mapping as host_external:container_internal
# -p 2222:22				// this means allow 2222 to be accesses from any ip on this host and map it to port 22 in the container
# <docker_image_id> 		// see docker images to fetch the right name & tag or id
# 							// after the Docker image id, we can specify all the flags supported by 'ccontainermain'
#							// see this page for more info https://github.com/zrml/ccontainermain

**Comment by poppogbr** [comment]
FROM centos:7

ENV TMP_INSTALL_DIR="/tmp/cachekit"

ENV ISC_PACKAGE_INSTANCENAME="CACHE" \
    ISC_PACKAGE_INSTALLDIR="/opt/ensemble/" \
    ISC_PACKAGE_UNICODE="Y"

RUN mkdir $TMP_INSTALL_DIR
WORKDIR $TMP_INSTALL_DIR


RUN yum -y update \
 && yum -y install which tar hostname net-tools wget \
 && yum -y clean all \ 
 && ln -sf /etc/locatime /usr/share/zoneinfo/Europe/Prague

COPY cache-2017.1.1.111.0su-lnxrhx64.tar $TMP_INSTALL_DIR/
RUN tar -xvf cache-2017.1.1.111.0su-lnxrhx64.tar -C .
RUN ./cinstall_silent
RUN rm -rf $TMP_INSTALL_DIR/*
RUN ccontrol stop $ISC_PACKAGE_INSTANCENAME quietly 


EXPOSE 57772 1972


WORKDIR /
ADD ccontainermain .

ENTRYPOINT ["/ccontainermain"]

**Comment by daimor** [comment]
And can you also try to run container with this command, and show output?
```
docker run -p 57779:57772 -p 1979:1972 cachedb:2017 -cconsole
```
or change in Dockerfile
```
ENTRYPOINT ["/ccontainermain", "-cconsole"]
```

**Comment by poppogbr** [comment]
i add -cconsole and i have this log:
$ docker run -p 57779:57772 -p 1979:1972 cache:2017 -cconsole
2017/11/13 10:19:01 Starting Caché...
2017/11/13 10:19:01 Seeked /opt/ensemble/mgr/cconsole.log - &{Offset:0 Whence:2}
2017/11/13 10:19:06 Caché started successfully
2017/11/13 10:19:06 Caché is up.

**Comment by poppogbr** [comment]
i change Dockerfile from
ISC_PACKAGE_INSTALLDIR="/opt/ensemble/"
to
ISC_PACKAGE_INSTALLDIR="/opt/ensemble"

and work it!!!

**Comment by daimor** [comment]
Interesting your output does not have cconsole.log with flag -cconsole
looks like you use some previous versions of ccontainermain, better to add downloading directly from github
```
 curl -L https://github.com/daimor/ccontainermain/raw/master/distrib/linux/ccontainermain -o /ccontainermain \
 && chmod +x /ccontainermain \
```

**Comment by poppogbr** [comment]
i have downloaded your containermain and this is log:
$ docker run -p 57780:57772 -p 1980:1972 cache2:2017 -cconsole
2017/11/13 10:51:50 Starting Caché...
2017/11/13 10:51:50 Seeked /opt/ensemble/mgr/cconsole.log - &{Offset:0 Whence:2}
2017/11/13 10:51:51 Something is preventing Caché from starting in multi-user mode,
2017/11/13 10:51:51 You might want to start the container with the flag -cstart=false to fix it.
2017/11/13 10:51:51 Error: Caché was not brought up successfully.

**Comment by daimor** [comment]
hm, strange

**Comment by poppogbr** [comment]
it's very strange. have you some suggest?

**Comment by zrml** [comment]
@poppogbr sorry I'm late on this one. It looks like you're all sorted.
@daimor could you please check why the cconsole.log is not outputted? has HP changed their lib in any way? Are we using it correctly or have they deprecated some flags?
thanks

**Comment by daimor** [comment]
I'll check it later, I've used this possibility a few days ago, and it worked well
@poppogbr can you try my previous builds, just to check how it works for you?
```
docker run -p 57775:57772 daimor/intersystems-cache:2017.1
```
it should show cconsole.log
