### ISSUE TITLE
Changing global buffers and etc

### ISSUE THREAD

**Issue by daimor** [zrml/ccontainermain#4]
How to be if I want to change some settings such as global/routines buffers or anything else.
Sure, I can use my pre-configured `cache.cpf` file stored outside from container, but it means that I should care about all of this content.
Looks like we need something like path for `cache.cpf` file just only with some changes

```
[config]
globals=0,0,1024,0,0,0
routines=128
```

and before starting caché it may extend original config file

**Comment by zrml** [comment]
@daimor (bear with me if i'm late but I don't see notification for some strange reason!)
I'm hoping Caché will offer a more dynamic API sometime soon.
Right now you'll have to configure it at "Dockerfile" creation time with something like sed.

If you don't have a chance to use the above, run the container, edit the params you're after and docker commit that container to suit your needs.
HTH

**Comment by daimor** [comment]
Now I do it with Installer manifest, while with Dockerfile, but it means that pre-builded container will have fixed paarmeters. Hope in future InterSystems may give to us more flexibility in this case.

**Comment by zrml** [comment]
Exactly! That way we just prepare an artifact (the container) and you can use it in dev, test. production and things are tuned as you spin up the instance.
