### ISSUE TITLE
Just a note for others trying to build their own containers

### ISSUE THREAD

**Issue by thurber** [zrml/ccontainermain#5]
Hi there,

Thanks so much for providing this code! I'm working on building a Cache + HealthShare container for a development environment and this repo is helping me a lot. Just wanted to leave a note here for others that might have run into a similar problem as me:

When trying to install Cache 2016.2 beta on CentOS 7, I kept getting a "gzip is required for Cache installation error" which was confusing because `gzip` was already installed. The actual issue was that `which` was not installed, and one of the checks in the installation script was using `which` to decide if `gzip` was installed or not. Adding `which` to my `yum -y install` line in the Dockerfile solved the problem!

**Comment by zrml** [comment]
@thurber Thank you very much for your comment on the issue and the resolution! 
I have not noticed this issue before. However, I have noticed issues doing updates to the OS container (Tutum CentoOS). 
Thanks
