### ISSUE TITLE
While Caché is failed to start, docker thinks that everithing is OK

### ISSUE THREAD

**Issue by daimor** [zrml/ccontainermain#6]
I think in case when Caché can't be started in normal mode, this container should exit as not started. Because it is difficult to see whats going wrong, while you don't see logs.

```
fhir-ensemble_1  | Cache is started in single user mode.
fhir-ensemble_1  | To log into Cache, type:
fhir-ensemble_1  |     ccontrol session ENSEMBLE -B
fhir-ensemble_1  | and D ^STURECOV for help recovering from this error.
fhir-ensemble_1  | 09/26/16-14:36:13:485 (36) 0 Write daemon started with strategy #1
fhir-ensemble_1  | 2016/09/26 14:36:13 Something is preventing Caché from starting in multi-user mode,
fhir-ensemble_1  | 2016/09/26 14:36:13 You might want to start the container with the flag -cstart=false to fix it.
fhir-ensemble_1  | 2016/09/26 14:36:13 Caché is up.
```

**Comment by zrml** [comment]
Hi @daimor 
Thanks for your comment.

I would argue that it's important to understand what is going on and having the container up helps me in logging back in, checking the environment, the logs etc.

I think structured logs could help more in this area to be honest.
The feedback information in the container log and your extension to see the cconsole.log allows us to investigate the issue and being able to quickly test the issue inside the container, to me has great value vs having to stop/start with new config etc.

More to the point, when you have a cluster of containers and a couple don't start up, I'd like to be able to investigate that by logging into them...

I guess we are talking about "handling strategies" and there is probably value in both... not sure...

**Comment by daimor** [comment]
But I think, if container not start at all, because of some issues inside, it will be easier to see.
Ok, then we can add some flag, like check-alive, or so on, and if this flag is defined ccontainermain should be really sure that everything is ok, we can even try to connect inside, check license for example, and so on. Some test which said that server is really ready to work.

**Comment by zrml** [comment]
Then don't you have to Docker engine to check if the container is up?
We risk to try to be too clever and complicate things...
I'm not saying I'm right... just bouncing off ideas...

**Comment by daimor** [comment]
Yes unfortunately Docker think that container is up while it is alive (process with pid 1 inside), and even we can't yet check while this container started. Like when I have two linked containers, and caché's container starts too slow, next fails when trying to connect to the database. And I don't know how to solve it yet. But when I have linked services, I expect to see if Caché fail to start, my application also should fail. And in this case, I will see that something goes wrong, and can investigate.

**Comment by zrml** [comment]
OK so we are back talking about
1) The container is up and running; it has not failed to start; PID 1 exists and all is well from a container point of view.
2) Caché, for whatever reason failed to start.

Correct?

**Comment by daimor** [comment]
yes

**Comment by zrml** [comment]
Docker run does not return a status.
If you have a flag it will still be found in the log output which you have anyway.
What would you propose?
thanks @daimor

**Comment by daimor** [comment]
Yes, we still can read logs from container if it is down.
So, flag will be good 
for this task we can made --fail-if-single-mode

**Comment by zrml** [comment]
I see what you're saying... I was thinking something else.
I'd prefer something like
-fail-if-troubled 
as a description as we might want to use it in other cases...

**Comment by daimor** [comment]
yes, this name will be better, with future new checks

**Comment by daimor** [comment]
I'll change in pull request for this flag

**Comment by zrml** [comment]
OK, thanks
